### ISSUE TITLE
Hardcoded table prefix in SQL query

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#1]
Hello,

1. I found a hard-coded table prefix in the SQL query. Please use curly braces: https://moodledev.io/docs/5.0/apis/core/dml#table-prefix
![image](https://github.com/user-attachments/assets/12796fe7-643d-4a37-a695-2bf4a3bae45c)
![image](https://github.com/user-attachments/assets/70adde58-25cd-4b3a-b8b0-800206d92608)

2. Please review the SQL coding style documentation how to format the SQL code:
https://moodledev.io/general/development/policies/codingstyle/sql

3. Use get_in_or_equal() method to use IN() operator:
https://moodledev.io/docs/4.5/apis/core/dml#get_in_or_equal
![image](https://github.com/user-attachments/assets/8c0ab002-a7c9-4242-8daf-fa333f34ae01)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

thank you for your advice. It's better in V1.1.

Best regards
Stephan

**Comment by WaetzigS** [comment]
solved in new version and well tested until moodle 4.4. Moodle 4.5 needs another package.
