### ISSUE TITLE
Missing Privacy API implementation

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#11]
Hello,

Each Moodle plugin is required to implement the Privacy API. Even if your plugin does not store any personal information, the `null` Privacy Provider class must be implemented to inform Moodle of this.

For further details, please refer to the documentation:

[Privacy API Checklist](https://moodledev.io/general/community/plugincontribution/checklist#privacy)
[Moodle Privacy API Documentation](https://moodledev.io/docs/4.5/apis/subsystems/privacy)

**Comment by WaetzigS** [comment]
Thank you very much for the comment. 
In the next version, you can see the Privacy information.

![image](https://github.com/user-attachments/assets/52c58634-cbdc-423c-af07-71b897b38b62)

**Comment by WaetzigS** [comment]
solved in new version
