### ISSUE TITLE
Legacy classes implementation

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#12]
Hello,
please consider implementing classes using namespaces and Moodle classes autoloading.
For further details, you can refer to the:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#class-names

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

it's converted to namespace in the next version.

![image](https://github.com/user-attachments/assets/0d8abf4e-a24a-46f1-9acb-830e7c52a62c)

**Comment by WaetzigS** [comment]
solved in new version
