### ISSUE TITLE
Delete not needed code and files

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#13]
Hello,
please remove not needed and not used code and files.

1. Old classes/whatsapp.php class
![image](https://github.com/user-attachments/assets/24c80be9-c413-4d31-9cf3-0df5d7b26d24)

2. The access.php file and capability definition which is not used anywhere
![image](https://github.com/user-attachments/assets/5097d0d1-a96d-4186-87c3-8c62c9bb7038)

3. The message.php file with message definitions which are not used anywhere
![image](https://github.com/user-attachments/assets/cc9115b0-e1a5-4247-aec4-4429e94a3264)

4. Commented code in lib.php file:
![image](https://github.com/user-attachments/assets/93e5484f-ce3a-49da-b777-1b3a8a39ea75)

5. Commented and old code in whatsapp.js file:
![image](https://github.com/user-attachments/assets/892e52f8-6132-473a-aa32-c34f0278e60c)

**Comment by WaetzigS** [comment]
ok

**Comment by WaetzigS** [comment]
in net version it's better
