### ISSUE TITLE
Non-English translations and comments

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#14]
Hello,
please review 'en' file translations and comments/variables in the plugin:
https://moodledev.io/general/community/plugincontribution/checklist#english

![image](https://github.com/user-attachments/assets/32917e00-d4fb-4b4b-a415-eb64724075d5)
![image](https://github.com/user-attachments/assets/7b4b9b01-2045-48bf-b5ca-d98b46ebc099)

**Comment by WaetzigS** [comment]
ok, in the next version, the comments are deleted.
