### ISSUE TITLE
Incorrect XML structure in install.xml

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#15]
Hello,
please review install.xml and fix the issue for the 'message' field:
![image](https://github.com/user-attachments/assets/df83919f-05b6-43aa-980c-4012b1fedd39)

You can generate/validate the install.xml file using XMLDB Editor: https://moodledev.io/general/development/tools/xmldb

**Comment by WaetzigS** [comment]
ok
