### ISSUE TITLE
Not fully implemented Privacy API

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#16]
Hello,
as you added a new DB table and stored user IDs in this table - you need to fully implement the Privacy Provider with the ability to export and delete user data.
![image](https://github.com/user-attachments/assets/6ef0fd69-0bf5-4bde-ba6a-e43db9a0e4c2)
![image](https://github.com/user-attachments/assets/1ea5ec49-e194-4ad0-bdd9-cdaa8a1785e2)

Please review more documentation: https://moodledev.io/docs/4.5/apis/subsystems/privacy
In addition, you can validate the implementation with CLI utils: https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils

**Comment by WaetzigS** [comment]
Thank you for the advice. In the next version you see there is a better provider.php

![image](https://github.com/user-attachments/assets/6856cbe1-0950-4840-876d-6aeb33365add)
