### ISSUE TITLE
POST params processing

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#18]
Hello,
I found you are using PARAM_RAW expected parameter type for all optional_param/required_param. This PARAM_RAW parameter type will not clean any data from the POST/GET request.
![image](https://github.com/user-attachments/assets/c348f07c-b89a-4db7-90af-dfe226dbd750)

It is better to use specific types like: PARAM_INT, PARAM_SEQUENCE, etc. 

![image](https://github.com/user-attachments/assets/00e5289c-f98a-4fd4-ba51-ef4a3ddaf800)
![image](https://github.com/user-attachments/assets/f22730c0-1ed7-40f8-9785-6cbbf0916894)

**Comment by WaetzigS** [comment]
ok, it's changed in new version

**Comment by WaetzigS** [comment]
It's changed in the new version
