### ISSUE TITLE
Incorrect plugin configuration name usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#19]
Hello,
I found the incorrect plugin name in all get/set plugin configurations. The correct plugin name is 'local_whatsappgen' which should be used for configuration definition and usage.

![image](https://github.com/user-attachments/assets/61a31b66-7f9e-4b63-a43d-5b324486ed2e)
![image](https://github.com/user-attachments/assets/c06cb510-d847-42af-b930-deea338e0851)
![image](https://github.com/user-attachments/assets/769fd30c-f94d-49a1-9512-e0a78e0834c6)

**Comment by WaetzigS** [comment]
changed in new version.

**Comment by WaetzigS** [comment]
it's in the new versions
