### ISSUE TITLE
DB error on Postgre

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#2]
Hello,
I got a DB error on Postgre. Please review:

![image](https://github.com/user-attachments/assets/06afdd6a-71f7-4216-ae0e-39a8e64f706e)

Error reading from database

[More information about this error](https://docs.moodle.org/401/en/error/moodle/dmlreadexception)

Debug info: ERROR: function group_concat(character varying) does not exist
LINE 9: (SELECT group_concat(grou.name)
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
SELECT
us.id as id ,
us.firstname as firstname ,
us.lastname as lastname ,
us.phone1 as phone1 ,
us.phone2 as phone2 ,
us.email as email ,
us.country as country ,
(SELECT group_concat(grou.name)
FROM m_groups grou
JOIN m_groups_members member ON member.userid = us.id AND member.groupid = grou.id
WHERE
grou.id = member.groupid AND
member.userid = us.id AND
grou.courseid = $1
) as groupname
FROM
m_user us

WHERE
us.id IN ( 163,168,399,499,693,741,748,800,887 )
[array (
0 => '2',
)]
Error code: dmlreadexception×Dismiss this notification
Stack trace:
line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 341 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
line 1027 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 90 of /local/whatsappgen/local_whatsappgen.php: call to pgsql_native_moodle_database->get_records_sql()
line 233 of /local/whatsappgen/local_whatsappgen.php: call to whatsapp->get_content()

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

I apologize for the oversight. PostgreSQL does not support group_concat, which I was not aware of. In Version 1.1, group_concat is no longer used, so this issue will be resolved. The script now checks if each user is in groups within the foreach loop.

![image](https://github.com/user-attachments/assets/8365a0f8-5efb-48e0-83da-edb4c05a085c)


Best regards
Stephan

**Comment by WaetzigS** [comment]
solved in new version
