### ISSUE TITLE
Incorrect configuration usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#3]
Hello,
please use get_config() function to get the plugin configuration: https://moodledev.io/general/development/abc/faq#config_plugin-table

![image](https://github.com/user-attachments/assets/d66b35c2-95a4-43a4-be09-095582c39449)
![image](https://github.com/user-attachments/assets/ed640b8b-55e8-420e-bb17-64668bc49386)
![image](https://github.com/user-attachments/assets/cf0ebd4b-655b-4d67-8e99-1326a53587b9)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

thank you very much for the advice. In V1.1 you won't see a get_record from the config table.

Best regards
Stephan

**Comment by WaetzigS** [comment]
solved in new version
