### ISSUE TITLE
Code clean-up

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#4]
Hello,
please clean-up the code: remove commented code, not-used variables, etc.

![image](https://github.com/user-attachments/assets/e0f6aecb-bc05-4a56-b7b0-39b5ec7c8d75)
![image](https://github.com/user-attachments/assets/4a80fc2d-c9fd-4a4e-a232-6ad927480220)
![image](https://github.com/user-attachments/assets/96a395c1-e1c4-4964-96e3-3dd0cb1b41d5)
![image](https://github.com/user-attachments/assets/be1da064-92ec-4840-9eec-8a919440bbcc)
![image](https://github.com/user-attachments/assets/6517c0fc-c02f-4561-ad12-650da3f18b20)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

thanks for the advice. In version 1.1 the there will be no old or unusual line 👍 

Best regards
Stephan

**Comment by WaetzigS** [comment]
solved in new version
