### ISSUE TITLE
Missing Header and Copyright Information in Files

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#6]
Hello,
I noticed that some files are missing the correct header and copyright/author notes. According to the [Moodle Plugin Contribution Checklist](https://moodledev.io/general/community/plugincontribution/checklist#boilerplate), all files should include the common boilerplate header with an explicit GPL license statement at the beginning.
Please review and update the plugin accordingly.

![image](https://github.com/user-attachments/assets/9b77be4c-6084-46f9-bad6-1965cf966d84)
![image](https://github.com/user-attachments/assets/cf3e3e96-bba9-4fc0-91be-e7e64754510b)
![image](https://github.com/user-attachments/assets/b28994f4-773e-49ad-b46b-5f2ba2f4e3b7)
![image](https://github.com/user-attachments/assets/008ce054-a774-48c5-9d18-8c929580a8fa)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

thank you for the advice. The header are implemented in Version 1.1

**Comment by WaetzigS** [comment]
solved in new version
