### ISSUE TITLE
Missing capabilities and course access validation

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#7]
Hello,
I noticed that the local_whatsappgen.php file only includes require_login() for validation.

Please add course access validation and implement a check for teacher capabilities to restrict access to this page for other users.
In addition, please consider using sesskey validation on form submission.

For reference, please review the Access API documentation:
https://moodledev.io/docs/4.3/apis/subsystems/access

![image](https://github.com/user-attachments/assets/bb7410ba-be12-4fc2-b480-2e002eb4307d)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

thanks for the important advice. That's right. I set the proofing, that the user can only generate with the specific role from the settings. So the users without the role gets a redirect to the dashboard.

![image](https://github.com/user-attachments/assets/7cd4f506-34f7-4418-b3b8-ac7e78ecabf2)

Release is in 1.1

Merry Christmas and best regards

**Comment by WaetzigS** [comment]
solved in new version
