### ISSUE TITLE
Do not disable JS caching

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#8]
Hello,

Please do not disable the JavaScript cache (cachejs). It should only be controlled via config.php or admin settings and is allowed to be disabled only on development sites. Disabling it forces all JS source files to load individually instead of the minimized and built versions, impacting performance.

![image](https://github.com/user-attachments/assets/8972adae-48f5-4faf-b61d-8101bdc938cc)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

thank you for the advice. In the new version, it's out.

Best regards
Stephan

**Comment by WaetzigS** [comment]
solved in new version
