### ISSUE TITLE
Use Message API to create notifications

### ISSUE THREAD

**Issue by volodymyrdovhan** [WaetzigS/moodle-local_whatsappgen#9]
Hello,
Please avoid inserting notifications directly into the database table.

Instead, review and use the Message API to send notifications to users:
https://moodledev.io/docs/4.4/apis/core/message

![image](https://github.com/user-attachments/assets/d82a829b-003b-464a-8d80-21344bc56b1b)

**Comment by WaetzigS** [comment]
Hello Volodymyr Dovhan,

thanks a lot. The notification is only for sent messages (what I read). The messages in the plugin are just created; if the phonenumber is incorrect or the user does not send it, the recipient will not receive it. To address this, I created a new table for the created messages. If the admin wants to track these messages, they can now be recorded in the **whatsappgen_messages** table.

Best regards
Stephan

**Comment by WaetzigS** [comment]
sorry, I forgot. I release it in version 1.1

**Comment by WaetzigS** [comment]
solved in new version
